version: '3.4'
services:
    omission_api:
      image: ertanakpinaroglu/omission_api:latest
      build:
        context: .
        dockerfile: ./Dockerfile
      environment:
        - TZ=Europe/Istanbul
      ports:
        - "9000:80"
      deploy:
        replicas: 2
        update_config:
          parallelism: 10
          delay: 1s
        restart_policy:
          condition: on-failure